// <auto-generated />
using System;
using ArtExhibit.BackEnd.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtExhibit.BackEnd.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225124750_SalesEntityAndImplementation")]
    partial class SalesEntityAndImplementation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ArtExhibit.BackEnd.Domain.Entities.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Peinture"
                        },
                        new
                        {
                            id = 2,
                            name = "Sculpture"
                        },
                        new
                        {
                            id = 3,
                            name = "Photographie"
                        },
                        new
                        {
                            id = 4,
                            name = "Dessin"
                        });
                });

            modelBuilder.Entity("ArtExhibit.BackEnd.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Beautiful oil painting capturing the golden hour over the Eiffel Tower",
                            Name = "Sunset Over Paris",
                            Price = 1250.5f,
                            Tags = "[\"landscape\",\"paris\",\"sunset\",\"oil\"]",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Modern abstract painting with vibrant colors",
                            Name = "Abstract Dreams",
                            Price = 890f,
                            Tags = "[\"abstract\",\"modern\",\"colorful\"]",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Life-size bronze sculpture of an ancient warrior",
                            Name = "Bronze Warrior",
                            Price = 5500f,
                            Tags = "[\"bronze\",\"warrior\",\"ancient\",\"statue\"]",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Elegant marble sculpture depicting a ballet dancer",
                            Name = "Dancing Figure",
                            Price = 3200f,
                            Tags = "[\"marble\",\"ballet\",\"dance\",\"elegant\"]",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Black and white photography series of Parisian streets",
                            Name = "Urban Streets",
                            Price = 450f,
                            Tags = "[\"photography\",\"black-white\",\"urban\",\"paris\"]",
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Stunning landscape photography collection",
                            Name = "Nature's Beauty",
                            Price = 680f,
                            Tags = "[\"nature\",\"landscape\",\"photography\",\"color\"]",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Detailed charcoal drawing of a human face",
                            Name = "Portrait Study",
                            Price = 320f,
                            Tags = "[\"portrait\",\"charcoal\",\"drawing\",\"realistic\"]",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Collection of detailed plant and flower sketches",
                            Name = "Botanical Sketches",
                            Price = 280f,
                            Tags = "[\"botanical\",\"sketches\",\"nature\",\"pencil\"]",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ArtExhibit.BackEnd.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("FinalPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<float>("StartingPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ItemId");

                    b.HasIndex("SellerId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyerId = 4,
                            EndDate = new DateOnly(2024, 1, 20),
                            FinalPrice = 850f,
                            ItemId = 2,
                            SellerId = 1,
                            StartDate = new DateOnly(2024, 1, 15),
                            StartingPrice = 890f,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            BuyerId = 1,
                            EndDate = new DateOnly(2024, 2, 10),
                            FinalPrice = 450f,
                            ItemId = 5,
                            SellerId = 3,
                            StartDate = new DateOnly(2024, 2, 1),
                            StartingPrice = 450f,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            BuyerId = 2,
                            EndDate = new DateOnly(2024, 3, 15),
                            FinalPrice = 0f,
                            ItemId = 8,
                            SellerId = 3,
                            StartDate = new DateOnly(2024, 3, 5),
                            StartingPrice = 280f,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            BuyerId = 4,
                            EndDate = new DateOnly(2024, 2, 28),
                            FinalPrice = 3100f,
                            ItemId = 4,
                            SellerId = 2,
                            StartDate = new DateOnly(2024, 2, 20),
                            StartingPrice = 3200f,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            BuyerId = 2,
                            EndDate = new DateOnly(2024, 3, 20),
                            FinalPrice = 0f,
                            ItemId = 1,
                            SellerId = 1,
                            StartDate = new DateOnly(2024, 3, 10),
                            StartingPrice = 1250.5f,
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("ArtExhibit.BackEnd.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Marie",
                            LastName = "Dubois",
                            UserEmail = "marie.dubois@example.com",
                            UserName = "marie_artist",
                            UserPhone = "0612345678",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Pierre",
                            LastName = "Martin",
                            UserEmail = "pierre.martin@example.com",
                            UserName = "pierre_sculptor",
                            UserPhone = "0623456789",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Sophie",
                            LastName = "Bernard",
                            UserEmail = "sophie.bernard@example.com",
                            UserName = "sophie_photo",
                            UserPhone = "0634567890",
                            UserTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Jean",
                            LastName = "Admin",
                            UserEmail = "admin@example.com",
                            UserName = "admin_user",
                            UserPhone = "0645678901",
                            UserTypeId = 2
                        });
                });

            modelBuilder.Entity("ArtExhibit.BackEnd.Domain.Entities.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ArtExhibit.BackEnd.Domain.Entities.Item", b =>
                {
                    b.HasOne("ArtExhibit.BackEnd.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtExhibit.BackEnd.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArtExhibit.BackEnd.Domain.Entities.Sale", b =>
                {
                    b.HasOne("ArtExhibit.BackEnd.Domain.Entities.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtExhibit.BackEnd.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtExhibit.BackEnd.Domain.Entities.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Item");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ArtExhibit.BackEnd.Domain.Entities.User", b =>
                {
                    b.HasOne("ArtExhibit.BackEnd.Domain.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
